# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc836b4221491435c20588f6e03e4fcb5de5f3cdd6c6316ffbde385bab594db956d99426a92da28817fd4ac5423f0942629b9a5f1a6846e592b6bbd033fdc4d0

test:
  secret_key_base: c0bc80b9985a5f0b1afff0375c250745a5545ea82d7e22383cf824884b77b8286b2333f1672b5fd9a60d4d4a26b38c57235a945233cda95a2442e1e7c2ec5225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
